apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limitrange
  namespace: quota-demo-ns
spec:
  limits:
  - default:
      memory: 300Mi
    defaultRequest:
      memory: 50Mi
    type: Container  



# kc describe limitrange <limit-range-name> -n quota-demo-ns
# here there is not need to set the pod resource limit to be set as we are using limitRange.