apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-demo-ns
  namespace: akashhr
spec:
  hard:
    pods: "2"
    configmaps: "1"


# resource quota defines the total number of resource that can be deployed in the particular namespace of the cluster. 
# resource can be pods, replicaset, configmaps, jobs, cronjobs, services, deployment, daemonsets,replicaset,statefulsets.
# resource quota applies only for namespace and not for entire cluster
# main aim for resource quota is to ensure every cluster user gets the fair quota of the cluster
# and not each user consume all the cluster resources.

# kc -n quota-demo-ns get quota
# kc describe quota <reosurce-quota-name> -n quota-demo-ns
# kc get cm -n quota-demo-ns
# kc create configmap cm1 --from-literal=name=akashhr -n <akashhr>
# kc create configmap cm2 --from-literal=name=akashhr -n <akashhr>   # this gives error as it exceeds resource-quota.


# kc run nginx0 --image=nginx --replicas=1 -n quota-demo-ns
# kc run nginx1 --image=nginx --replicas=1 -n quota-demo-ns
# kc describe quota <resource-quota-name> -n quota-demo-ns
# kc run nginx2 --image=nginx --replicas=1 -n quota-demo-ns  # this gives error as exceeds reosurce limit
# kc get all -n quota-demo-ns


# kc -n quota-demo-ns scale deploy <deployment-name> --replicas=2
# kc -n quota-demo-ns describe replicaset <replicaset-name> | less



