apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
type: Opaque
data:
  username: <base64 encoded value>          # echo -n 'username' | base64
  password: <base64 encoded value>          # echo -n 'password' | base64



# 2 ways to create secret 
# 1) through yaml
# 2) kc create secret generic <secret-name> --from-literal=username=akash --from-literal=password=mypassword
  


# kc get secrets
# kc get secret <secret-name> -o yaml | less 
# kc describe secret <secret-name>
# kc exec -it <pod-name> sh                         # when there is one container in a pod
# > env | grep myusername
# > echo $myusername
# kc exec -it <pod-name> -c <container-name> --sh     # when tehre are multiple container inside a pod


# How to use secret inside pod/container?
# sceret can be mounted as environment variable or as a volume inside the pod/container.
# after updating secret should we need to restart the pod , for pod to take the updated secrets.

# any sensitive information that you donot want to put it in container like password , ssh keys are
# updaed through the secrets

