apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:   
  # volumes:                       # mounting secrtes as a volume to pods
  # - name: secret-volume
  #   secret:
  #     secretName: secret-demo
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    # volumeMounts:                   # mounting volume when mounting secrets as a volume mount
    # - name: secret-volume
    #   mountPath: /mydata
    env:                            # mounting secrtes as a env variable in container specification
      - name: myusername
        valueFrom:
          secretKeyRef:
            name: secret-demo
            key: username


# We should either mount secret as a environment variables or as a voulme not both