apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
type: Opaque
immutable: true                             # This makes config map immutable
data:
  username: <base64 encoded value>          # echo -n 'username' | base64
  password: <base64 encoded value>          # echo -n 'password' | base64


# once secret made as immutable we can not make it as mutable only way is to delet it and create a new one.