# kc run nginx --image nginx --replicas 4
# kc expose deploy nginx --port 80 --type Nodeport       # verify this by accessing nay of the worker nodeip:port
# kc autoscale deploy nginx --min 1 --max5 --cpu-percent 20
#                      or

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 20  # If cpu utiliztion of  crosses 20 % then HPA will lick off


# We need to set resource limits for horizontal pod autoscaling in the pod/deployment file refer the image
# image indicates ecah pod cannot use more than 0.1 core

# kc describe hpa <hpa-name>

